[package]
name = "rustDB"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
block-modes = "0.8.1"
block-padding = "0.3.3"
hex = "0.4.3"
hex-literal = "1.0.0"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
